version: '2'
services:
  alerta:
    image: alerta/alerta-web
    ports:
      - "9010:8080"
    depends_on:
      - db
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:alerta,alerta.kellgari.local'
    environment:
      - DEBUG=1 
      - DATABASE_URL=mongodb://db:27017/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - PLUGINS=reject,blackout,normalise,enhance
      - INSTALL_PLUGINS=normalise,enhance
    restart: always
  db:
    image: mongo
    restart: always
volumes:
  alerta-config:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/alerta-config
       host: 172.16.4.6
       onRemove: retain
  alerta-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/alerta-data
       host: 172.16.4.6
       onRemove: retain
