version: '2'
.catalog:
  name: Alerta
  version: latest
  description: Alert dashboard
services:
  aleta:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8090
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  db:
    scale: 1
    start_on_create: true
