version: "2"
services:
  tiddlywiki:
    image: mazzolino/tiddlywiki
    container_name: tiddlywiki
    environment:
      - TZ=Australia/Brisbane
    volumes:
      - tiddlywiki-data:/var/lib/tiddlywiki
    ports:
      - 9380:8080
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '9380'
      traefik.frontend.rule: 'Host:tiddlywiki,tiddlywiki.kellgari.local'
volumes:
  tiddlywiki-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/tiddlywiki-data
      onRemove: retain

