version: "2"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Australia/Brisbane
    volumes:
      - grocy-data:/config
    ports:
      - 9283:80
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:grocy.kellgari.local'
      traefik.domain: 'kellgari.local'
  barcodebuddy:
    image: f0rc3/barcodebuddy-docker:latest
    container_name: barcodebuddy
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Australia/Brisbane
    volumes:
      - barcodebuddy-data:/config
    ports:
      - 9284:80
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:barcodebuddy.kellgari.local'
      traefik.domain: 'kellgari.local'
volumes:
  grocy-data:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/grocy-data
      onRemove: retain
  grocy-data:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/barcodebuddy-data
      onRemove: retain
