version: "2"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Australia/Brisbane
    volumes:
      - grocy-data:/config
    ports:
      - 9283:80
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:grocy,grocy.kellgari.local'
      traefik.domain: 'kellgari.local'
volumes:
  grocy-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/grocy-data
      onRemove: retain

