version: '2'
services:
  influxdb:
    image: influxdb:alpine
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "4242:4242"
      - "2003:2003"
    environment:
      - TZ="Australia/Brisbane"
      - INFLUXDB_ADMIN_USER=true
      - INFLUXDB_ADMIN_BIND_ADDRESS=8083
      - INFLUXDB_DB=telegraf
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUX_ADMIN_USER=root
      - INFLUX_ADMIN_PASSWORD=root
      - INFLUX_USER=user
      - INFLUX_USER_PASSWORD=user
    volumes:
      - influx-data:/var/lib/influxdb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8086'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:influxdb,influxdb.kellgari.local'
  kapacitor:
    image: kapacitor:alpine
    ports:
      - "9092:9092"
    environment:
      - TZ="Australia/Brisbane"
      - KAPACITOR_HOSTNAME=kapacitor.kellgari.local
      - KAPACITOR_LOGLEVEL=INFO
      - KAPACITOR_REPORTING_ENABLED=false
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  chronograf:
    image: chronograf:alpine
    ports:
      - "8888:8888"
    environment:
      - TZ="Australia/Brisbane"
    volumes:
      - chronograf-data:/var/lib/chronograf
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8888'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:chronograf,chronograf.kellgari.local'
volumes:
  influx-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/influx-data
       host: 172.16.4.6
       onRemove: retain
  chronograf-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/chronograf-data
       host: 172.16.4.6
       onRemove: retain
