version: '2'
services:
  influxdb:
    image: influxdb:alpine
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "4242:4242"
      - "2003:2003"
    environment:
      - TZ="Australia/Brisbane"
      - INFLUXDB_ADMIN_USER=true
      - INFLUXDB_ADMIN_BIND_ADDRESS=8083
      - INFLUXDB_DB=telegraf
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUX_ADMIN_USER=root
      - INFLUX_ADMIN_PASSWORD=root
      - INFLUX_USER=user
      - INFLUX_USER_PASSWORD=user
    volumes:
      - influx-data:/var/lib/influxdb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8086'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:influxdb,influxdb.kellgari.local'
  telegraf:
    image: telegraf:alpine
    ports:
      - "8125:8125"
      - "8092:8092/udp"
      - "8094:8094"
    environment:
      - TZ="Australia/Brisbane"
    volumes:
      - telegraf-config:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  influx-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/influx-data
       host: 172.16.4.6
       onRemove: retain
  telegraf-config:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/telegraf-config
       host: 172.16.4.6
       onRemove: retain
