version: '2'
.catalog:
  name: Influx DB and Telegraf
  version: v0.7
  description: Influx timeseries database and Telegraf monitoring
services:
  influxdb:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8086
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  kapacitor:
    scale: 1
    start_on_create: true
  chronograf:
    scale: 1
    start_on_create: true
  telegraf:
    scale: 1
    start_on_create: true
