version: '2'
.catalog:
  name: Influx DB
  version: v0.5
  description: Influx timeseries database
services:
  influxdb:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8086
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  kapacitor:
    scale: 1
    start_on_create: true
  chronograf:
    scale: 1
