version: '2'
.catalog:
  name: Influx DB and Telegraf
  version: v0.5
  description: Influx timeseries database and Telegraf monitoring
services:
  influxdb:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8086
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
<<<<<<< HEAD
  kapacitor:
    scale: 1
    start_on_create: true
  chronograf:
    scale: 1
=======
  telegraf:
    scale: 1
    start_on_create: true
>>>>>>> 9108c45bfc5c5ca4f2a5f0f949f5f0503a30103f
