version: '2'
.catalog:
  name: Influx DB
  version: v0.5
  description: Influx timeseries database
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: influxdb
        source_port: 8086
        target_port: 8086
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  influxdb:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8086
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  influxdb-volume:
    scale: 1
    start_on_create: true
