version: '2'

services:
  netbox:
    image: netboxcommunity/netbox:latest
    ports:
      - "8111:80"
    environment:
      - TZ=Australia/Brisbane
      - SECRET_KEY=abcdefg12345678
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.domain: 'kellgari.local'
    restart: unless-stopped

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netbox

volumes:
  netbox-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/hera/containers/netbox-data
       host: 10.0.100.20
       onRemove: retain
