version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    privileged: true
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '8123:8123/tcp'
      - '554:554/tcp'
      - '554:554/udp'
      - '1900:1900/udp'
      - '3689:3689/tcp'
      - '5350:5350/udp'
      - '5350:5350/tcp'
      - '5351:5351/udp'
      - '5351:5351/tcp'
      - '5353:5353/udp'
      - '5353:5353/tcp'
      - '51827:51827/tcp'
      - '51827:51827/udp'
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    volumes:
      - homeassistant-config:/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity: "ha"
    network_mode: host
  appdaemon:
    image: acockburn/appdaemon:latest 
    environment:
      - TZ=Australia/Brisbane
    volumes:
      - homeassistant-appdaemon:/conf
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
  mqtt:
    image: eclipse-mosquitto
    environment:
      - TZ=Australia/Brisbane
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  homeassistant-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-config
      onRemove: retain
  homeassistant-appdaemon:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-appdaemon

