version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    privileged: true
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '8123:8123/tcp'
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    volumes:
      - homeassistant-config:/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity: "ha"
  appdaemon:
    image: acockburn/appdaemon:latest 
    environment:
      - TZ=Australia/Brisbane
      - HA_URL="http://homeassistant.homeassistant:8123"    
    volumes:
      - homeassistant-appdaemon:/config

volumes:
  homeassistant-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-config
      onRemove: retain
  homeassistant-appdaemon:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-appdaemon

