version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    privileged: true
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '8123:8123/tcp'
      - '554:554/tcp'
      - '554:554/udp'
      - '1900:1900/udp'
      - '3689:3689/tcp'
      - '5350:5350/udp'
      - '5350:5350/tcp'
      - '5351:5351/udp'
      - '5351:5351/tcp'
      - '5353:5353/udp'
      - '5353:5353/tcp'
      - '51827:51827/tcp'
      - '51827:51827/udp'
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - homeassistant-config:/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label: "ha=true"
      traefik.enable: 'true'
      traefik.port: '8123'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:homeassistant,homeassistant.kellgari.local'
    network_mode: host
  mqtt:
    image: eclipse-mosquitto
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '1883:1833/tcp'
      - '8883:8833/tcp'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label: "ha=true"
    network_mode: host
  node-red:
    image: nodered/node-red-docker:v8
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '1880:1880/tcp'
    volumes:
      - homeassistant-nodered:/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '1880'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:node-red,node-red.kellgari.local'
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    environment:
      - TZ=Australia/Brisbane
    devices:
      - "/dev/ttyACM2:/dev/ttyACM0"
    volumes:
      - zigbee2mqtt-data:/app/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label: "ha=true"
volumes:
  homeassistant-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-config
      onRemove: retain
  homeassistant-nodered:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-nodered
  zigbee2mqtt-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/homeassistant-zigbee2mqtt
      onRemove: retain
