version: '2'
services:
  unifi:
    image: jacobalberty/unifi:stable
    ports:
      - "8080:8080" 
      - "8443:8443" 
      - "8843:8843" 
      - "8880:8880" 
      - "3478:3478/udp"
      - "6789:6789" 
      - "10001:10001/udp"
    environment:
      - TZ="Australia/Brisbane"
    volumes:
      - unifi-data:/unifi
  unms:
    image: oznu/unms:latest  
    restart: always
    ports:
      - 8081:80
      - 8444:443
    environment:
      - TZ=Australia/Brisbane
volumes:
  unifi-data:
     driver_opts:
       export: /mnt/media/containers/unifi-data
       host: 172.16.4.6
       onRemove: retain
     driver: rancher-nfs
