version: '2'
services:
  unifi:
    image: linuxserver/unifi
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080" 
      - "8081:8081" 
      - "8443:8443" 
      - "8843:8843" 
      - "8880:8880" 
      - "6789:6789" 
    environment:
      - TZ="Australia/Brisbane"
    volumes:
      - unifi-config:/config
volumes:
  unifi-config:
     driver_opts:
       export: /mnt/media/containers/unifi-config
       host: 172.16.4.6
       onRemove: retain
     driver: rancher-nfs
