version: '2'
services:
  unifi:
    image: jacobalberty/unifi:stable
    ports:
      - "8080:8080" 
      - "8443:8443" 
      - "8843:8843" 
      - "8880:8880" 
      - "3478:3478/udp"
      - "6789:6789" 
      - "10001:10001/udp"
    environment:
      - TZ="Australia/Brisbane"
    volumes:
      - unifi-data:/unifi
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label: "unifi=true"
      traefik.enable: 'true'
      traefik.port: '8443'
      traefik.protocol: 'https'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:unifi.kellgari.local'
  unms:
    image: oznu/unms:latest  
    restart: always
    ports:
      - 8081:80
      - 8444:443
    environment:
      - TZ=Australia/Brisbane
      - PUBLIC_HTTPS_PORT=8444
      - PUBLIC_WS_PORT=8444
      - SECURE_LINK_SECRET=cUeWqR3u3Wi7lJRTokahEjpG
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label: "unms=true"
      traefik.enable: 'true'
      traefik.port: '443'
      traefik.protocol: 'https'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:unms.kellgari.local'
volumes:
  unifi-data:
     driver_opts:
       export: /mnt/media/containers/unifi-data
       host: 10.0.100.10
       onRemove: retain
     driver: rancher-nfs
