version: '2'
services:
  dev-jira:
    image: dchevell/jira-core
    privileged: true
    environment:
      - TZ=Australia/Brisbane
      - JVM_MINIMUM_MEMORY=384m
    ports:
      - '8080:8080/tcp'
    volumes:
      - dev-jira-data:/var/atlassian/application-data/jira
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:jira-dev,jira-dev.kellgari.local'
    network_mode: host
  postgres:
    image: postgres
    privileged: true
    environment:
      - TZ=Australia/Brisbane
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432/tcp'
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
    network_mode: host
volumes:
  dev-jira:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/dev-jira-data
      onRemove: retain
  postgres:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/dev-jira-postgres-data
      onRemove: retain
