version: '2'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "8111:80"
    environment:
      - TZ=Australia/Brisbane
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=root
      - IPAM_DATABASE_WEBHOST=%
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.domain: 'kellgari.local'
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Australia/Brisbane
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - TZ=Australia/Brisbane
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=phpipam
    user: nobody
    restart: unless-stopped
    volumes:
      - phpipam-data:/var/lib/mysql

volumes:
  phpipam-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/phpipam-data
       host: 172.16.4.6
       onRemove: retain
