version: '2'
services:
  gitea:
    image: gitea/gitea:1.3.0
    volumes:
      - gitea-data:/data
    links:
      - db:db
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'gitea'
    volumes:
      - gitea-db:/var/lib/mysql
volumes:
  gitea-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/gitea-data
      onRemove: retain
  gitea-db:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/gitea-db



