version: '2'
services:
  gitea:
    image: gitea/gitea:latest
    restart: always
    ports:
      - 3000:3000
      - 2222:22
    volumes:
      - gitea-data:/data
    environment:
      - TZ="Australia/Brisbane"
    labels:
      traefik.enable: 'true'
      traefik.port: '3000'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:gitea,gitea.kellgari.local'
volumes:
  gitea-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/gitea-data
      onRemove: retain



