version: '2'
services:
  gitea:
    image: gitea/gitea:latest
    ports:
      - 3000:3000
      - 2222:22
    volumes:
      - gitea-data:/data
    links:
      - db:db
volumes:
  gitea-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/gitea-data
      onRemove: retain



