name: netbox
description: NetBox IP address management
version: 0
category: Network
maintainer: Simon Inglis
license: GPL
projectURL: https://github.com/simoninglis/rancher/tree/master/templates/netbox
