version: '2'
services:
  mongodb:
    image: mongo:3
    user: nobody
    group_add:
      - 65534
    volumes:
      - mongo-data:/data/db
  elasticsearch:
    image: elasticsearch:6.8.6
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:3.2
    volumes:
      - graylog-data:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.kellgari.local:6280/
      - GRAYLOG_IS_MASTER=TRUE
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 6280:9000
      # Syslog TCP
      - 1514:1514
      # Edgerouter Syslog UDP
      - 1514:1514/udp
      # FreeNAS Syslog TCP
      - 1545:1545
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label:  "graylog=true"
      traefik.enable: 'true'
      traefik.port: '6280'
      traefik.frontend.rule: 'Host:graylog,graylog.kellgari.local'

volumes:
  mongo-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/graylog-mongo-data
      onRemove: retain
  es-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/graylog-es-data
      onRemove: retain
  graylog-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/graylog-data
      onRemove: retain

