version: '2'
.catalog:
  name: Graylog
  version: v0.10
  description: A centralised logging solution
services:
  mongodb:
    scale: 1
    start_on_create: true
  elasticsearch:
    scale: 1
    start_on_create: true
  graylog:
    scale: 1
    start_on_create: true
