version: "2"
services:
  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    environment:
      - TZ=Australia/Brisbane
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS=wikijs
      - DB_NAME=wiki
    ports:
      - 9480:3000
      - 9580:3443
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '9480'
      traefik.frontend.rule: 'Host:wikijs,wikijs.kellgari.local'
  db:
    image: postgres:11-alpine
    container_name: db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijs
      POSTGRES_USER: wikijs
    restart: unless-stopped
    volumes:
      - wikijs-data:/var/lib/postgresql/data
volumes:
  wikijs-data:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/wikijs-data
      onRemove: retain

