version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Australia/Brisbane
    volumes:
      - heimdall-data:/config
    ports:
      - 7280:80
      - 7680:443
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:heimdall.kellgari.local'
volumes:
  hemidall-data:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/heimdall-data
      onRemove: retain

