version: '2'
services:
  plex:
    image: plexinc/pms-docker
    environment:
      - TZ=Australia/Brisbane
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - PLEX_CHANGE_CONFIG_DIR_OWNERSHIP=false
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    volumes:
      - plex-config:/config
      - media:/data
    network_mode: ${NET}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  plex-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/plex-config
      onRemove: retain
  media:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/media
      onRemove: retain

