version: '2'
.catalog:
  name: Plex Server
  version: v0.5
  description: Plex Media Server
  questions:
    - variable: "PLEX_UID"
      type: "string"
      label: "PLEX_UID"
      description: Plex Unix user ID to assume .  Defaults to 'nobody'
      default: 65534
    - variable: "PLEX_GID"
      type: "string"
      label: "PLEX_GID"
      description: Plex Unix group ID to assume.  Defaults to 'nobody'
      default: 65534
    - variable: "PLEX_CLAIM"
      type: "string"
      label: "PLEX_CLAIM"
      description: Plex server claim token.   Go to https://www.plex.tv/claim/ to get the token.
    - variable: "PLEX_ADVERTISE_IP"
      type: "string"
      label: "PLEX_ADVERTISE_IP"
      description: URL to advertise this server available on (ie. via Plex internet name service)
      default: http://172.16.4.14:32400
services:
  plex:
    scale: 1
    start_on_create: true
