version: '2'
services:
  plex:
    image: linuxserver/plex
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${PORT}
    volumes:
      - ${PATHCONFIG}:/config
      - ${PATHMEDIA}:/data
    network_mode: ${NET}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  data:
    driver: rancher-nfs
    diver_opts:
      host: 172.16.4.6
      exportBase: /mnt/media/media
  config:
    driver: rancher-nfs
    diver_opts:
      host: 172.16.4.6
      exportBase: /mnt/media/containers/plex-config
