version: '2'
services:
  plex:
    image: linuxserver/plex
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${PORT}
    volumes:
      - plex-config:/config
      - media:/data
      - /var/run/rancher/storage/rancher-nfs.sock
    network_mode: ${NET}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  plex-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      exportBase: /mnt/media/containers/plex-config
      onRemove: retain
  media:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      exportBase: /mnt/media/media
      onRemove: retain

