version: '2'
.catalog:
  name: Plex Server
  version: v0.5
  description: Plex Media Server
  questions:
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of Plex external:internal
      default: 32400:32400
    - variable: "PATHCONFIG"
      type: "string"
      label: "Config Path"
      description: persistang Path to your Plex Config (/home/nick/plex, ...); use "config" as "Config Path" to use rancher-nfs
      default: 'config'
    - variable: "PATHMEDIA"
      type: "string"
      label: "Media Path"
      description: the Path to your library (/media, or a nfs mount /mnt, ...)
      default: '/media'
    - variable: "PUID"
      type: "string"
      label: "PUID"
      description: GroupID (not required)
      default: 1100
    - variable: "PGID"
      type: "string"
      label: "PGID"
      description: PGID (not required)
      default: 1100
    - variable: NET
      description: "select Network type"
      label: "Network"
      type: enum
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
services:
  plex:
    scale: 1
    start_on_create: true
