version: '2'
services:
  grafana:
    image: appcelerator/grafana
    ports:
      - "3000:3000"
    environment:
      - TZ="Australia/Brisbane"
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
      - GRAFANA_PLUGIN_LIST=natel-discrete-panel grafana-piechart-panel
      - INFLUXDB_PROTO=http
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=telegraf
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
      - INFLUXDB_IS_GRAFANADB=true
    volumes:
      - grafana-config:/var/lib/grafana
    labels:
      traefik.enable: 'true'
      traefik.port: '3000'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:grafana,grafana.kellgari.local'
volumes:
  grafana-config:
     driver_opts:
       export: /mnt/hera/containers/grafana-config
       host: 10.0.100.20
       onRemove: retain
     driver: rancher-nfs
