version: '2'
services:
  grafana:
    image: appcelerator/grafana
    ports:
      - "3000:3000"
    environment:
      - TZ="Australia/Brisbane"
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
      - INFLUXDB_PROTO=http
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=telegraf
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
      - INFLUXDB_IS_GRAFANADB=true
    volumes:
      - grafana-config:/var/lib/grafana
volumes:
  grafana-config:
     driver_opts:
       export: /mnt/media/containers/grafana-config
       host: 172.16.4.6
       onRemove: retain
     driver: rancher-nfs
