version: '2'
.catalog:
  name: Grafana
  version: v0.5
  description: Graphing and dashboards
  questions:
    - variable: INFLUXDB_HOST
      label: INFLUXDB_HOST
      required: true
      default: influxdb
      type: string
services:
  grafana:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3000
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
