version: '2'
services:
  deepstack:
    image: deepquestai/deepstack
    restart: always
    ports:
      - 7032:5000
    environment:
      - TZ="Australia/Brisbane"
      - VISION-DETECTION=True
    labels:
      traefik.enable: 'true'
      traefik.port: 7032
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:deepstack,deepstack.kellgari.local'

