version: '2'
services:
  deepstack:
    image: deepquestai/deepstack
    restart: always
    ports:
      - 7032:5000
    environment:
      - TZ="Australia/Brisbane"
      - VISION-DETECTION=True
      - VISION-SCENE=True
    volumes:
      - deepstack-data:/datastore
    labels:
      traefik.enable: 'true'
      traefik.port: 5000
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:deepstack,deepstack.kellgari.local'

volumes:
  deepstack-data:
     driver: rancher-nfs
     driver_opts:
       export: /mnt/media/containers/deepstack-data
       host: 10.0.100.10
       onRemove: retain
