version: '2'
services:
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Australia/Brisbane
      - UID=${OPENVPN_UID}
      - GID=${OPENVPN_GID}
    ports:
      - '1194:1194/udp'
    volumes:
      - openvpn-config:/etc/openvpn
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.affinity:host_label:  "openvpn=true"
volumes:
  openvpn-config:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/openvpn-config
      onRemove: retain

