version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      - TZ=Australia/Brisbane
      - UID=${SONARR_UID}
      - GID=${SONARR_GID}
    ports:
      - '8989:8989/tcp'
    volumes:
      - sonarr-config:/config
      - media-tv:/media/TV
      - media-downloads:/downloads
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8989'
      traefik.frontend.rule: 'Host:sonarr,sonarr.kellgari.local'
volumes:
  sonarr-config:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.10
      export: /mnt/media/containers/sonarr-config
      onRemove: retain
  media-tv:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.10
      export: /mnt/media/media/TV
      onRemove: retain
  media-downloads:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.10
      export: /mnt/media/media/Downloads

