version: '2'
.catalog:
  name: Sonarr
  version: v0.6
  description: Sonarr
  questions:
    - variable: "SONARR_UID"
      type: "string"
      label: "SONARR_UID"
      description: Sonarr Unix user ID to assume .  Defaults to 'nobody'
      default: 65534
    - variable: "SONARR_GID"
      type: "string"
      label: "SONARR_GID"
      description: Sonarr Unix group ID to assume.  Defaults to 'nobody'
      default: 65534
services:
  sonarr:
    scale: 1
    start_on_create: true
  radarr:
    scale: 1
    start_on_create: true
  lidarr:
    scale: 1
    start_on_create: true
