version: '2'
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 8087:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - TZ="Australia/Brisbane"
      - DRONE_OPEN=true
      - DRONE_HOST=172.16.4.16
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://172.16.4.16:3000
      - DRONE_SECRET=abcd12345

  drone-agent:
    image: drone/agent:latest
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ="Australia/Brisbane"
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=abcd12345
