version: '2'
services:
 smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - TZ=Australia/Brisbane
      - PUID=1001
      - PGID=1001
    volumes:
      - smokeping-config:/config
      - smokeping-data:/data
    ports:
      - 8089:80
    mem_limit: 4096m
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
      traefik.enable: 'true'
      traefik.port: '8089'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:smokeping,smokeping.kellgari.local'
volumes:
  smokeping-config:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/smokeping-config
      onRemove: retain
  smokeping-data:
    driver: rancher-nfs
    driver_opts:
      host: 10.0.100.20
      export: /mnt/hera/containers/smokeping-data
      onRemove: retain


