version: '2'
services:
  sync:
    image: linuxserver/syncthing
    environment:
      - TZ=Australia/Brisbane
      - UID=${SYNCTHING_UID}
      - GID=${SYNCTHING_GID}
    ports:
      - '8384:8384/tcp'
      - '22000:22000/tcp'
    volumes:
      - sync-config:/config
      - media-downloads:/mnt/Download
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
volumes:
  sync-config:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/containers/sync-config
      onRemove: retain
  media-downloads:
    driver: rancher-nfs
    driver_opts:
      host: 172.16.4.6
      export: /mnt/media/media/Downloads

