version: '2'
services:
  facebox:
    image: machinebox/facebox
    restart: always
    ports:
      - 8081:8080
    environment:
      - TZ="Australia/Brisbane"
      - MB_KEY=${MB_KEY}
    labels:
      traefik.enable: 'true'
      traefik.port: '8081'
      traefik.domain: 'kellgari.local'
      traefik.frontend.rule: 'Host:facebox,facebox.kellgari.local'

