version: '2'
.catalog:
  name: Facebox
  version: latest
  description: Facebox face recognition
   questions:
    - variable: "MB_KEY"
      label: "Machine Box key"
      description: ""
      default: 5000
      required: true
      type: "string"
services:
  facebox:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3000
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
